### ISSUE TITLE
Update to `crypto-bigint=0.6` and `crypto-primes=0.6` when they are released.

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/synedrion#104]
As a part of the update:
- we can dissolve the `UintLike`/`UintLikeMod` traits since they're now implemented as `Integer` and `Monty` in `crypto-bigint`.
- we can use `Odd` for the modulus in `PaillierPublicKey` (need to add support for serialization to `Odd` though)
- possibly use `BoxedUint` for integers?

**Comment by dvdplm** [comment]
I've been looking at this and it seems to be a pretty big upgrade. I'm happy to continue tinkering with it, but it will not be quick from the look of it.

The `HasWide` trait is a bit problematic – it would require `generic_const_exprs` to implement for `Uint<L>`s and after having tried various `typenum` shenanigans it seems impossible. I think using the `WideningMul` trait from `crypto-bigint` is probably better, but it is pretty impactful so not sure how that will workout.

The `Signed<L>` type is what I'm tinkering with atm. It doesn't have a great replacement in `crypto-bigint` and I'm hesitant to embark on implementing `Integer` and `Monty` traits for it. Possibly I should take a step back and look deeper into how `Signed` and `Bounded` are actually used. Perhaps there's a way to get rid of them and use the types from `crypto-bigint` instead?

On that note, would you mind elaborating a bit on your comment here, "possibly used `BoxedUint` for integers?"

**Comment by fjarri** [comment]
No problem, I appreciate you looking at it anyway.

> The HasWide trait is a bit problematic

Yes, I think `HasWide` will probably have to stay manual.

> On that note, would you mind elaborating a bit on your comment here, "possibly used BoxedUint for integers?"

So there is now a `BoxedUint` type in `crypto-bigint` which is not generic over the number of limbs, and just keeps the data in a `Box` (it still has a fixed size, but it is runtime and can be changed, basically like a `Vec`). If we used that, there would be no need in `HasWide`, and probably in `Bounded`, because I could just use the `BoxedUint`'s bound (it is more granular, changes by 64 bit increments, but that still does the job). The problem here is that it is slower than stack-allocated integers, although I cannot say off the top of my head by how much. I think I have some tests in `crypto-primes`.

> The `Signed<L>` type is what I'm tinkering with atm. It doesn't have a great replacement in `crypto-bigint` and I'm hesitant to embark on implementing `Integer` and `Monty` traits for it. 

I don't think you need to, it's currently `Signed<T: UintLike>`, so it'll just be `Signed<T: Integer>`. It may be the only change you will need to do there. `Signed` is needed in ZK proofs which, unfortunately, operate with signed integers. Also both `Signed` and `Bounded` are used to avoid sending a lot of zeros when we use, say, 1200 bits out of a 2000 bit integer (which comes up in ZK proofs pretty often).
