### ISSUE TITLE
Audit?

### ISSUE THREAD

**Issue by tmpfs** [entropyxyz/synedrion#121]
Hi @fjarri , I noticed you made some commits ([here](https://github.com/entropyxyz/synedrion/tree/8663210122898d53eaf1c0344d0c5c120e54621d) and [here](https://github.com/entropyxyz/synedrion/tree/897423f87108b70cc9cb0ddfca9a62d8b74e69bc)) that referenced an audit; was it an internal or external audit?

If it was an internal audit are there plans for an external audit once the library reaches the v1 milestone?

Thanks 🙏

**Comment by fjarri** [comment]
It technically public, but I can't find the report at the moment, should be somewhere at https://research.nccgroup.com. Yes, we are planning another audit later this year when we have the threshold stuff and identifiable aborts fully operational.

**Comment by tmpfs** [comment]
Thanks @fjarri, thats's great! I can't find the report there either, do you have a copy or link you would be able to share please?

**Comment by fjarri** [comment]
I searched for the link again and couldn't find it. On the off-chance that it was private after all, I just sent the report to your email.

**Comment by toufic0710** [comment]
Hello, can I please have the report sent to my email as well?

**Comment by fjarri** [comment]
Sorry for the delay, sent.
