### ISSUE TITLE
Should totient be secret?

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/synedrion#148]
Since the RSA primes `p` and `q` are safe primes, the totient (`(p - 1) (q - 1)`) should be about as safe to publish as `p q`, since it'll still be a product of two large primes times 4.

**Comment by dvdplm** [comment]
I think not actually. Consider
n = p*q
phi(n) = (p-1)(q-1) = p*q - p - q + 1
If I know both n and phi( n) then I can reconstruct the sum of p and q like so: s = n + 1 - phi(n) = p*q + 1 - p*q + p + q - 1 = p + q

Knowing both the product and the sum of p and q would make factorizing them easy I think.

**Comment by fjarri** [comment]
Yeah I think that'll basically reduce factoring to solving a 2-nd order equation. Nevermind then :)
