### ISSUE TITLE
Zeroize `MontyParams` of RSA primes

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/synedrion#162]
Currently blocked by https://github.com/RustCrypto/crypto-bigint/issues/704.

In the `paillier` module, we have some `MontyParams` structures with moduli `p` and `q`, and some precomputed constants containing these params. These need to be zeroized when `crypto-bigint` supports it.

**Comment by AaronFeickert** [comment]
This functionality [has been merged](https://github.com/RustCrypto/crypto-bigint/pull/706).
